# Generated by Django 4.2 on 2023-12-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSuspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_name', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('dresscode', models.CharField(max_length=200, null=True)),
                ('incident_description', models.CharField(max_length=500, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
            ],
        ),
    ]
